### ISSUE TITLE
lim1 term

### ISSUE THREAD

**Issue by brankoju** [FlorianAdler/AlgebraBonn#8]
the second isomorphism in part 3 on page 175 pi_0(Hom(BGL_infty,fib(..))) = lim pi_0(Hom(BGL_n,fib(…))) is proven by using the milnor exact sequence. however, the lim1 term is not lim1 pi_1(Hom(BGL_n,ku)) (as claimed on page 176) but lim1 pi_1(Hom(BGL_n,fib(..))) .  it is not so obvious why this vanishes too, we actually need to use some mittag leffler stuff, a proof  (of an equivalent statement) can be found in quillens original paper, lemma 14 .2

**Comment by FlorianAdler** [comment]
Thanks for pointing that out! I fixed this, hopefully, in the latest update. "Hopefully" because after being confused by Quillen's notation, I gave a somewhat different argument ... or maybe it is really just Quillen's argument in different words. Anyway, I think it should work.
